# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e76cbc6b0b62203cbfc51cbe10c5ff4eb349da186d4059d2ce3066d8c14892a3845d84c9c3bb662939afbffb7754e71d2b7bda463cf142214badac494167ab

test:
  secret_key_base: cbfdd373f881bf22d40ef5fef0f0e2a1084c09d0ab985dd8825179fc170d062aa933ce41a31a03e387ecd31f4806839dda2562f51bae29c505f61f04fd76419c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
